uilibs/uiprotect

- src/uiprotect/data/base.py
- remove the _set objects since they are always returned from their respective functions and never accessed directly
- create _get_unifi_remaps_set to avoid re-creating a set every time a message is processed
- cache the _get_protect_* calls so we do not have to call the pure-python code and can stay in native code to fetch their values
> feat: refactor protect object subtype bucketing

- src/uiprotect/api.py
- src/uiprotect/cli/backup.py
- src/uiprotect/data/base.py
- src/uiprotect/data/devices.py
- src/uiprotect/data/nvr.py
- src/uiprotect/data/types.py
- src/uiprotect/utils.py
refactor: remove useless .keys() calls
`keys()` is the default so its not needed in these places
> refactor: remove useless .keys() calls

- .coveragerc
- src/uiprotect/api.py
The reformatting runs even if debug logging is disabled
> feat: guard debug logging that reformats data in the arguments

- src/uiprotect/data/bootstrap.py
#22 tried to reuse the time, but the code paths/objects are mutually exclusive so there is no reason to fetch it until we need it because its never reused.
> fix: remove useless time check

- src/uiprotect/websocket.py
The Websocket disconnect error logger message was missing the variable
> fix: missing url param in websocket disconnected error log message

- src/uiprotect/api.py
- src/uiprotect/data/base.py
- src/uiprotect/data/bootstrap.py
- src/uiprotect/data/devices.py
- src/uiprotect/data/nvr.py
- src/uiprotect/data/user.py
We should avoid the public self.api method inside the object since there is no reason to check again as the objects themselves could not be created if it was unset
Avoid ever setting self._api to `None`
> refactor: use internal self._api inside the object

- src/uiprotect/data/bootstrap.py
there were three sets of keys to be removed. Remove all the keys needed in a single loop instead
of having multiple remove paths
> refactor: consolidate logic to remove keys

- src/uiprotect/data/bootstrap.py
_get_frame_data is only now ever called in one place, remove it since it only serves to make it harder to understand what is going on in process_ws_packet
Long term we should refactor the `Bootstrap` class to be `BootstrapWithStats` so we can avoid all the complexity in the base class as stats are only used for tests
> feat: remove _get_frame_data helper

- src/uiprotect/data/bootstrap.py
Instead of fetching camera/lights/sensors twice, pass them to the processor and avoid the call if its unset
> feat: cleanup duplicate object lookups in event processing

- src/uiprotect/data/base.py
related issue https://github.com/home-assistant/core/issues/119534
> fix: use None instead of ... for PrivateAttr

- src/uiprotect/data/base.py
- src/uiprotect/data/bootstrap.py
- tests/test_api.py
partially reverts #68 since HA tests are resetting the properties by adjusting the underscore values.
> fix: revert to using protected attrs for property cache

- src/uiprotect/data/bootstrap.py
refactoring error introduced in #85 that I forgot to remove when I was testing
> fix: ensure camera and chime keys are not included in the base ignored set

- src/uiprotect/data/base.py
ensure update_from_dict creates the object is it was previously None
license plate metadata can change from none to and object via an update
> fix: ensure update_from_dict creates the object is it was previously None

- src/uiprotect/api.py
- tests/test_api.py
- tests/test_api_polling.py
calling update always now always does an update instead of having to guess if one will happen or not. This will allow us to remove all sorts of complex logic
> feat!: remove the force flag from update

- src/uiprotect/api.py
_raise_for_status when raise_exception is not set
status would be unbound in this case
> fix: _raise_for_status when raise_exception is not set

- .coveragerc
coveragerc fails to omit cli and tests.
I went to start looking as what was missing coverage in base.py and realized the coveragerc didn't work as expected
> fix: coveragerc fails to omit cli and tests

- src/uiprotect/data/base.py
- src/uiprotect/data/devices.py
- src/uiprotect/data/nvr.py
every object had an asyncio.Queue, asyncio.Lock, and asyncio.Event only create them the first time they are needed
> fix: make creation of update sync primitives lazy

- src/uiprotect/data/devices.py
- src/uiprotect/utils.py
- tests/data/test_camera.py
The mocking in the test was using an int instead
of a timedelta. Add new property to
get the seconds
> fix: reflection of chime duration seconds

- src/uiprotect/api.py
We were doing complex url joins when we were only joining paths we already hard code internally which meant everything had to get parsed into url parts, joined together, and than reassembled
> feat: speed up url joins

- src/uiprotect/_compat.py
- src/uiprotect/api.py
- src/uiprotect/data/base.py
- src/uiprotect/data/types.py
- src/uiprotect/data/websocket.py
v1.0.0 moved the public api to propcache.api
see https://github.com/aio-libs/propcache/pull/21
see https://github.com/aio-libs/propcache/issues/18 
see https://github.com/aio-libs/propcache/pull/19
> feat: add support for propcache v1.0.0+
