uilibs/uiprotect

- README.md
> - If pre-commit.ci is failing, try `pre-commit run -a` for further information.
> - If CI / test is failing, try `poetry run pytest` for further information.
> fix: small fixes for README.md

- src/uiprotect/data/bootstrap.py
- Avoid generating lists of stats keys and throwing them away if websocket stats are not enabled
- Only fetch time if it will actually be used
> feat: improve performance of process websocket packets

- src/uiprotect/data/bootstrap.py
- src/uiprotect/utils.py
Use a single cached function to normalize mac addresses to avoid doing it differently in different places
> feat: use a single function to normalize mac addresses

- src/uiprotect/data/bootstrap.py
- add some types to the dict value lookups
- avoid linear search of models in _process_add_packet
- move the remove packet code around to avoid invalid lookups
> feat: cleanup websocket add/remove packet processing

- src/uiprotect/data/bootstrap.py
- avoid duplicate lookups
- reduce code
> feat: cleanup processing camera events

- src/uiprotect/data/bootstrap.py
reduce duplicate code to process sensor events
> refactor: reduce duplicate code to process sensor events

- src/uiprotect/data/bootstrap.py
use new _event_is_in_range helper in _process_camera_event
> refactor: use new _event_is_in_range helper in _process_camera_event

- src/uiprotect/data/types.py
There is no need to look this up over and over again as it never changes
> feat: make audio_type a cached_property

- src/uiprotect/data/base.py
> feat: add debug logging when saving device changes

- src/uiprotect/data/bootstrap.py
there was a missing elif
related issue #57
> fix: refactoring error in _process_add_packet

- .github/workflows/ci.yml
note that 1.10.16 is broken so we exclude that
> chore: add pydantic 1.x to the ci

- src/uiprotect/data/bootstrap.py
small cleanups to bootstrap code
> feat: small cleanups to bootstrap code

- src/uiprotect/data/bootstrap.py
> fix: add missing eventStats key to STATS_KEYS

- src/uiprotect/data/bootstrap.py
small cleanup to get device functions
> feat: small cleanup to get device functions

- src/uiprotect/data/base.py
refactor protect obj methods to use comprehensions
> feat: refactor protect obj methods to use comprehensions

- src/uiprotect/data/bootstrap.py
- src/uiprotect/data/nvr.py
use tuples for all the delete iterators
> refactor: use tuples for all the delete iterators

- src/uiprotect/data/base.py
remove and consolidate unused code in base
> refactor: remove and consolidate unused code in base

- src/uiprotect/data/websocket.py
- tests/test_api_ws.py
improve performance of websocket packet processing
> feat: improve performance of websocket packet processing

- src/uiprotect/data/devices.py
avoid writing out some more key converts
> refactor: avoid writing out some more key converts

- src/uiprotect/data/devices.py
the key should have been poped
https://github.com/uilibs/uiprotect/commit/851c7987b772a185fd4c448dddd9e180fd4f16da
> fix: refactoring error in 83

- src/uiprotect/websocket.py
decrease websocket logging for known errors
The logging was a bit chatty for known issues
> feat: decrease websocket logging for known errors

- src/uiprotect/websocket.py
handle websocket auth errors on restart
> feat: handle websocket auth errors on restart

- src/uiprotect/data/base.py
- tests/data/test_common.py
exclude_fields would mutate the classvar
> fix: exclude_fields would mutate the classvar

- src/uiprotect/data/base.py
remove unreachable api in data checks
> fix: remove unreachable api in data checks

- src/uiprotect/data/base.py
> fix: small tweaks to compact code

- pyproject.toml
> fix: license classifier

- src/uiprotect/data/nvr.py
cleanup some additional dupe attr lookups
> feat: cleanup some additional dupe attr lookups

- src/uiprotect/data/nvr.py
small cleanups to devices
- use is for enums
- avoid len checks when value will be false
> feat: small cleanups to devices

- src/uiprotect/data/websocket.py
small cleanups to packet packing/unpacking
> feat: small cleanups to packet packing/unpacking

- src/uiprotect/data/devices.py
get_last_smart_detect_event looked up the event twice
> feat: small cleanups to smart detect lookups

- tests/data/test_camera.py
add test coverage for chime type
> chore: add test coverage for chime type

- .github/dependabot.yml
yarl has been updated as well as some other deps
> chore: update dependabot.yml to force dependabot run

- .github/workflows/docker.yml
> fix: docker builds

- pyproject.toml
- src/uiprotect/data/devices.py
- tests/conftest.py
- tests/data/test_camera.py
> chore: enable ruff SIM rules and fix all violations
